[battery]
format="[$percentage]($style) remaining "
disabled = false

[[battery.display]]
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 30
style = "yellow"

[[battery.display]]
threshold = 100
style = "green"


[time]
time_format = "%Hh%M"
format = "at [$time]($style) "
style = "bright-white"
disabled = false
