"$schema" = 'https://starship.rs/config-schema.json'

# see - https://www.nerdfonts.com/cheat-sheet

format = """
$battery\
$time\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$package\
$nodejs\
${custom.angular}\
$cmd_duration\
$status\
$line_break\
$character"""

[character]
success_symbol = "[\uf105](white)" # 
error_symbol = "[\uf467](red)" # 

[battery]
format = "[$percentage]($style) "

[[battery.display]]
threshold = 100
style = 'green'

[[battery.display]]
threshold = 50
style = 'orange'

[[battery.display]]
threshold = 25
style = 'red'

[[battery.display]]
threshold = 10
style = 'bold red'

[nodejs]
version_format='${raw}'
style = 'green'

[time]
disabled = false
format = "at [$time](white) | "
time_format = "%H:%M"

[custom.angular]
command = """
$pnpmDeps = (pnpm list "@angular/core" --json | ConvertFrom-Json)[0]
$pnpmDeps.dependencies.'@angular/core'.version
"""
when = """
$pnpmDeps = (pnpm list "@angular/core" --json | ConvertFrom-Json)[0]
if (-not $pnpmDeps.PSObject.Properties.Name.Contains("dependencies")) {
    exit 1
}

$projectDeps = $pnpmDeps.dependencies
if (-not $projectDeps.PSObject.Properties.Name.Contains("@angular/core")) {
    exit 1
}

exit 0
"""
shell = ['powershell', '-NoProfile', '-Command', '-']
format = "using [󰚿 $output](red)"
ignore_timeout = true
